//
// Created by shira on 9/10/19.
//

#ifndef C_VECTOR_OF_INTS_SHIRAZALTSMAN_VECTOR_TEST_H
#define C_VECTOR_OF_INTS_SHIRAZALTSMAN_VECTOR_TEST_H

void add_and_delet()
#endif //C_VECTOR_OF_INTS_SHIRAZALTSMAN_VECTOR_TEST_H
